theme: minima
title: In My End Is My Beginning
author: aadianna
email: alex.dianna_ux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You've heard the saying, "When you think it's all falling apart, you'll realize in time that it's all coming together." This blog is all about that kind of thing.
# You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.

# social links
twitter_username: alternativedjs # DO NOT include the @ character, or else the build will fail!
github_username:  aadianna # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
